name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Neovim ${{ matrix.nvim_version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        nvim_version: [stable, nightly]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Set up Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.nvim_version }}
    - name: Run tests
      run: make test
